import { BaseTool, type ToolArgs, ToolDefinition } from './BaseTool';
import { MessageContext } from '../core/MessageContext';
import { StickerUtils } from '../utils/StickerUtils';
import { logger } from '../utils/logger';
import { t } from '../utils/i18n';
import { getErrorMessage } from '../utils/errorUtils';
import { readFile } from 'fs/promises';
import { existsSync } from 'fs';

const log = logger.child({ module: 'MakeStickerTool' });

type StickerArgs = ToolArgs & {
  packname?: string;
  author?: string;
};

type RawMediaMessage = {
  message?: {
    imageMessage?: { mimetype?: string };
    videoMessage?: { mimetype?: string };
    documentMessage?: { mimetype?: string };
  };
};

function getRawMimeType(targetMessage: MessageContext | NonNullable<MessageContext['quoted']>): string {
  const rawMessage = targetMessage.rawMessage as RawMediaMessage | undefined;
  return rawMessage?.message?.imageMessage?.mimetype
    || rawMessage?.message?.videoMessage?.mimetype
    || rawMessage?.message?.documentMessage?.mimetype
    || '';
}

export class MakeStickerTool extends BaseTool<StickerArgs> {
  readonly name = 'sticker';
  readonly description = 'Converts an image or short video into a WhatsApp sticker.';
  readonly aliases = ['s', 'makesticker', 'createsticker'];
  readonly category = 'media';
  readonly permissions = 'user';
  override readonly triggerPatterns = [/^image\//i, /^video\//i];

  get definition(): ToolDefinition {
    return {
      type: 'function',
      function: {
        name: this.name,
        description: this.description,
        parameters: {
          type: 'object',
          properties: {
            packname: { type: 'string', description: 'Optional name of the sticker pack' },
            author: { type: 'string', description: 'Optional author of the sticker' },
          },
          required: [],
        },
      },
    };
  }

  async execute(args: StickerArgs, ctx: MessageContext): Promise<string> {
    if (!ctx.hasMedia && !ctx.quoted?.hasMedia) {
      return t(ctx.language, 'sticker.no_media');
    }

    try {
      const targetMessage = ctx.hasMedia ? ctx : ctx.quoted!;
      log.debug({ chatId: ctx.chatId, mime: targetMessage.mimeType }, 'Sticker creation started');

      if (!targetMessage.mediaPath) {
        await ctx.react?.('\u{1F4E5}');
        await ctx.mediaReady;
      }

      let buffer: Buffer | null = null;
      let mime = targetMessage.mimeType || '';

      if (targetMessage.mediaPath && existsSync(targetMessage.mediaPath)) {
        buffer = await readFile(targetMessage.mediaPath);
      } else if (ctx.downloadMedia) {
        await ctx.react?.('\u23F3');
        buffer = await ctx.downloadMedia();
        if (!mime) {
          mime = getRawMimeType(targetMessage);
        }
      } else {
        return t(ctx.language, 'sticker.download_not_supported');
      }

      if (!buffer) {
        return t(ctx.language, 'sticker.download_failed');
      }

      let webpBuffer: Buffer;
      if (mime.includes('image')) {
        webpBuffer = await StickerUtils.imageToWebp(buffer);
      } else if (mime.includes('video')) {
        webpBuffer = await StickerUtils.videoToWebp(buffer);
      } else {
        try {
          webpBuffer = await StickerUtils.imageToWebp(buffer);
        } catch {
          return t(ctx.language, 'sticker.unsupported_type', { mime });
        }
      }

      const packname = args.packname || 'Generated by';
      const author = args.author || 'ElastraX v7';
      const stickerBuffer = await StickerUtils.writeExif(webpBuffer, { packname, author });
      log.debug({ chatId: ctx.chatId, stickerSize: stickerBuffer.length }, 'Sticker WebP created');

      if (typeof ctx.sendSticker === 'function') {
        await ctx.sendSticker(stickerBuffer);
      } else {
        await ctx.reply(t(ctx.language, 'sticker.send_not_supported'));
      }

      return t(ctx.language, 'sticker.success');
    } catch (error: unknown) {
      log.error({ err: error, chatId: ctx.chatId }, 'Sticker creation failed');
      return t(ctx.language, 'sticker.error', { msg: getErrorMessage(error) });
    }
  }
}



