import { BaseTool, ToolDefinition } from './BaseTool';
import { MessageContext } from '../core/MessageContext';
import { StickerUtils } from '../utils/StickerUtils';
import { logger } from '../utils/logger';
import { t } from '../utils/i18n';

export class MakeStickerTool extends BaseTool {
  readonly name = 'sticker';
  readonly description = 'Converts an image or short video into a WhatsApp sticker.';
  readonly aliases = ['s', 'makesticker', 'createsticker'];
  readonly category = 'media';
  readonly permissions = 'user';

  get definition(): ToolDefinition {
    return {
      type: 'function',
      function: {
        name: this.name,
        description: this.description,
        parameters: {
          type: 'object',
          properties: {
            packname: { type: 'string', description: 'Optional name of the sticker pack' },
            author: { type: 'string', description: 'Optional author of the sticker' }
          },
          required: []
        }
      }
    };
  }

  async execute(args: Record<string, any>, ctx: MessageContext): Promise<string> {
    // 1. Verify media exists
    if (!ctx.hasMedia && !ctx.quoted?.hasMedia) {
      return t(ctx.language, 'sticker.no_media');
    }

    try {
      // 2. Download Media using MessageContext
      const targetMessage = ctx.hasMedia ? ctx : ctx.quoted!;

      if (!ctx.downloadMedia) {
         return t(ctx.language, 'sticker.download_not_supported');
      }

      await ctx.react?.('⏳'); // show working progress

      const buffer = await ctx.downloadMedia();

      if (!buffer) {
         return t(ctx.language, 'sticker.download_failed');
      }

      // 3. Determine type and convert to WebP
      // Extract mimetype from the raw message structure (Baileys specific fallback if needed)
      let mime = '';
      if (ctx.hasMedia) {
          const msg = ctx.rawMessage?.message;
          mime = msg?.imageMessage?.mimetype || msg?.videoMessage?.mimetype || msg?.documentMessage?.mimetype || '';
      } else {
          const msg = ctx.quoted?.rawMessage?.message;
          mime = msg?.imageMessage?.mimetype || msg?.videoMessage?.mimetype || msg?.documentMessage?.mimetype || '';
      }

      let webpBuffer: Buffer;

      if (mime.includes('image')) {
        webpBuffer = await StickerUtils.imageToWebp(buffer);
      } else if (mime.includes('video')) {
        webpBuffer = await StickerUtils.videoToWebp(buffer);
      } else {
        // Fallback: guess from buffer or reject
        // We will try to blindly convert as image if we are not sure
        try {
           webpBuffer = await StickerUtils.imageToWebp(buffer);
        } catch (e) {
           return t(ctx.language, 'sticker.unsupported_type', { mime });
        }
      }

      // 4. Write EXIF
      const packname = args.packname || 'Generated by';
      const author = args.author || 'ElastraX v7';

      const stickerBuffer = await StickerUtils.writeExif(webpBuffer, { packname, author });

      // 5. Send using provider's specific ability
      if (typeof ctx.sendSticker === 'function') {
         await ctx.sendSticker(stickerBuffer);
      } else {
         // Fallback if provider doesn't implement sendSticker
         await ctx.reply(t(ctx.language, 'sticker.send_not_supported'));
      }

      return t(ctx.language, 'sticker.success');

    } catch (e: any) {
      logger.error(e, 'Failed to make sticker tool');
      return t(ctx.language, 'sticker.error', { msg: e.message || 'Unknown error' });
    }
  }
}
