import { BaseTool, ToolDefinition } from './BaseTool';
import { MessageContext } from '../core/MessageContext';
import { StickerUtils } from '../utils/StickerUtils';
import { logger } from '../utils/logger';
import { t } from '../utils/i18n';
import { readFile } from 'fs/promises';
import { existsSync } from 'fs';

export class MakeStickerTool extends BaseTool {
  readonly name = 'sticker';
  readonly description = 'Converts an image or short video into a WhatsApp sticker.';
  readonly aliases = ['s', 'makesticker', 'createsticker'];
  readonly category = 'media';
  readonly permissions = 'user';

  get definition(): ToolDefinition {
    return {
      type: 'function',
      function: {
        name: this.name,
        description: this.description,
        parameters: {
          type: 'object',
          properties: {
            packname: { type: 'string', description: 'Optional name of the sticker pack' },
            author: { type: 'string', description: 'Optional author of the sticker' }
          },
          required: []
        }
      }
    };
  }

  async execute(args: Record<string, any>, ctx: MessageContext): Promise<string> {
    // 1. Verify media exists
    if (!ctx.hasMedia && !ctx.quoted?.hasMedia) {
      return t(ctx.language, 'sticker.no_media');
    }
    try {
      // 2. Await background media download (started immediately when the message was received).
      //    If the download is already done this resolves instantly; otherwise we wait.
      //    We show 📥 to let the user know we're fetching their media.
      const targetMessage = ctx.hasMedia ? ctx : ctx.quoted!;

      if (!targetMessage.mediaPath) {
        await ctx.react?.('📥');
        await ctx.mediaReady;
      }

      let buffer: Buffer | null = null;
      let mime = targetMessage.mimeType || '';

      if (targetMessage.mediaPath && existsSync(targetMessage.mediaPath)) {
        buffer = await readFile(targetMessage.mediaPath);
      } else if (ctx.downloadMedia) {
        // Fallback: download hasn't completed (e.g. expired CDN link) — try again directly.
        await ctx.react?.('⏳');
        buffer = await ctx.downloadMedia();
        if (!mime) {
          const msg = (targetMessage as any).rawMessage?.message;
          mime = msg?.imageMessage?.mimetype || msg?.videoMessage?.mimetype || msg?.documentMessage?.mimetype || '';
        }
      } else {
        return t(ctx.language, 'sticker.download_not_supported');
      }

      if (!buffer) {
         return t(ctx.language, 'sticker.download_failed');
      }

      // 3. Determine type and convert to WebP

      let webpBuffer: Buffer;

      if (mime.includes('image')) {
        webpBuffer = await StickerUtils.imageToWebp(buffer);
      } else if (mime.includes('video')) {
        webpBuffer = await StickerUtils.videoToWebp(buffer);
      } else {
        // Fallback: guess from buffer or reject
        // We will try to blindly convert as image if we are not sure
        try {
           webpBuffer = await StickerUtils.imageToWebp(buffer);
        } catch (e) {
           return t(ctx.language, 'sticker.unsupported_type', { mime });
        }
      }

      // 4. Write EXIF
      const packname = args.packname || 'Generated by';
      const author = args.author || 'ElastraX v7';

      const stickerBuffer = await StickerUtils.writeExif(webpBuffer, { packname, author });

      // 5. Send using provider's specific ability
      if (typeof ctx.sendSticker === 'function') {
         await ctx.sendSticker(stickerBuffer);
      } else {
         // Fallback if provider doesn't implement sendSticker
         await ctx.reply(t(ctx.language, 'sticker.send_not_supported'));
      }

      return t(ctx.language, 'sticker.success');

    } catch (e: any) {
      logger.error(e, 'Failed to make sticker tool');
      return t(ctx.language, 'sticker.error', { msg: e.message || 'Unknown error' });
    }
  }
}
